fedimg/services/ec2.py
Currently, if it fails we just know the exit code was '1' but not much else.
=> Try to log output from the pseudo-tty when we do ec2 stuff.

bin/kill_ec2_nodes.py
Otherwise it warns about not being able to log stuff.
=> Setup logging for cronjob

fedimg/services/ec2.py
=>  Dropped 'os' and 'ver' from the AWS_AMIS config

bin/kill_ec2_nodes.py
The latest version of libcloud changed the way we initialize the connection driver. This PR fixes in accordance to the upgrade notes.
=> cron: Update the cron according to the upgrade notes

fedimg/services/ec2.py
=> services.ec2: Log if the image was successfully made public

fedimg/utils.py
=> Fix the invalid syntax issue

bin/trigger_upload.py
=> scripts: Fix the manual upload trigger script

fedimg-conf.toml.example, fedimg/config.py, fedimg/services/ec2/ec2imguploader.py
=> services.ec2: Change the bucket name to more related to fedimg

fedimg/services/ec2/ec2imguploader.py
Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>
=> Error out if starting the task failed

fedimg/services/ec2/ec2imgpublisher.py, fedimg/utils.py, tests/test_utils.py
Fixes https://pagure.io/cloud-sig/issue/284
=> services.ec2: Deprecate the PV images

fedimg/services/ec2/ec2imguploader.py
=> fedimg.ec2: Add the support for Elastic Network Adapter

fedimg/consumers.py, fedimg/uploader.py, tests/test_consumers.py, tests/test_uploader.py
=> uploader: Set push_notifications to True when automatic upload

fedimg/consumers.py
=> consumer: Support F28 Atomic & Cloud messages

fedimg/services/ec2/ec2imguploader.py
=> services.ec2: Fix the volume_type attribute

fedimg/consumers.py
=> consumers: Ignore the Unsupported releases

bin/trigger_upload.py
=> scripts: Fix the script to send proper format of compose id

bin/trigger_upload.py
=> fedimg: Fix the script function argument order

fedimg/consumers.py
=> consumers: Fix the metadata handling for Rawhide messages

fedimg/consumers.py
=> fix trace for incorrect log function call

fedimg/services/ec2/ec2imguploader.py
=> services.ec2: Fix the ImportError in ec2imguploader

fedimg/utils.py
=> utils: Extract the raw first before processing
